[general]
import = [
  "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "Monaco", style = "Regular" }
bold = { family = "Monaco", style = "Bold" }
italic = { family = "Monaco", style = "Italic" }
size = 16

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

[window]
option_as_alt = "Both"
