nnoremap <Leader>m :Emodel 
nnoremap <Leader>c :Econtroller 
nnoremap <Leader>v :Eview 
nnoremap <Leader>h :Ehelper 
nnoremap <Leader>u :Eunittest 
nnoremap <Leader>f :Efunctionaltest 
nnoremap <Leader>i :Einitializer 
nnoremap <Leader>j :Ejavascript 
nnoremap <Leader>s :Estylesheet 
nnoremap <Leader>l :Elocale 
nnoremap <Leader>r :Rake
nnoremap da :A<CR>
nnoremap dr :R<CR>
