nnoremap <Leader>m :Emodel 
nnoremap <Leader>c :Econtroller 
nnoremap <Leader>v :Eview 
nnoremap <Leader>h :Ehelper 
nnoremap <Leader>u :Eunittest 
nnoremap <Leader>f :Efunctionaltest 
nnoremap <Leader>i :Eintegrationtest 
nnoremap <Leader>j :Ejavascript 
nnoremap <Leader>s :Estylesheet 
nnoremap <Leader>l :Elocale 
nnoremap <Leader>r :Rake
nnoremap dr :Rake<CR>
nnoremap _a :A<CR>
nnoremap _r :R<CR>
