nnoremap <Leader>m :Rmodel 
nnoremap <Leader>c :Rcontroller 
nnoremap <Leader>v :Rview 
nnoremap <Leader>h :Rhelper 
nnoremap <Leader>u :Runittest 
nnoremap <Leader>f :Rfunctionaltest 
nnoremap <Leader>i :Rintegrationtest 
nnoremap <Leader>j :Rjavascript 
nnoremap <Leader>s :Rstylesheet 
nnoremap <Leader>r :Rake
nnoremap <Leader>t :Rake<CR>
nnoremap _a :A<CR>
nnoremap _r :R<CR>
